rsync \
  -avh \
  --exclude='.bundle' \
  --exclude='.cache' \
  --exclude='.conda' \
  --exclude='.compose-cache' \
  --exclude='.daedalus' \
  --exclude='.docker' \
  --exclude='.dropbox-dist' \
  --exclude='.emacs.d/eln-cache' \
  --exclude='.gem' \
  --exclude='.gnupg' \
  --exclude='.gradle' \
  --exclude='.local' \
  --exclude='.npm' \
  --exclude='.nv' \
  --exclude='.platformio' \
  --exclude='.sbt' \
  --exclude='.stack' \
  --exclude='.vagrant.d/boxes' \
  --exclude='.xmonad' \
  --exclude='encfs' \
  --exclude='git' \
  --exclude='vagrantboxen' \
  --exclude='work' \
  /home/kranium/ \
  /armorydata/kranium/
