# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = 
    [
     "ahci"
     "ata_piix"
     "ehci_hcd"
     "ehci_pci"
     "fbcon"
     "hid"
     "hid_apple"
     "hid_generic"
     "i915"
     "ohci_pci"
     "uhci_hcd"
     "usb_storage"
     "usbhid"
     "xhci_hcd"
    ];
  boot.initrd.luks.devices = [{ name = "luksroot"; device = "/dev/disk/by-uuid/da7a4b5a-a6a5-4b55-8bf0-115615ce30a9"; }];
  boot.kernelModules = [ "kvm-intel" ];
  boot.blacklistedKernelModules = ["pcspkr" "snd_pcsp"];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luksroot";
      fsType = "ext4";
      options = "relatime,data=ordered,commit=600";
    };

  fileSystems."/tmp" =
    { device = "tmpfs";
      fsType = "tmpfs";
      neededForBoot = true;
    };

  fileSystems."/var/log" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/home/kranium/.cache" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/tmp" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8D19-BB5C";
      fsType = "vfat";
    };

  fileSystems."/Windows" =
    { device = "/dev/disk/by-uuid/E8FA2C4FFA2C1C76";
      options = "defaults,umask=022,uid=2000";
    };

  swapDevices =[ ];

  nix.maxJobs = 4;
}
