# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ "${config.boot.kernelPackages.broadcom_sta}" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/212b3cca-cf95-4adb-8045-3e6391ef8177";
      fsType = "ext4";
    };

  fileSystems."/MacOSX" =
    { device = "/dev/disk/by-uuid/8979d211-650a-34a5-b0eb-3116ec7c277b";
      fsType = "hfsplus";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/67E3-17ED";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = 8;
}
